name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
    using: composite
    steps:
        - uses: pnpm/action-setup@v4
          with:
              run_install: false

        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
              node-version-file: 'package.json'
              cache: 'pnpm'

        - name: Install Dependencies
          shell: bash
          run: pnpm i --no-frozen-lockfile
