export default {
    branchPrefix: 'renovate/',
    username: 'renovate-release',
    gitAuthor: 'Renovate Bot <bot@renovateapp.com>',
    onboarding: false,
    platform: 'github',
    forkProcessing: 'enabled',
    dryRun: 'full',
    groupName: 'all',
    labels: ['type:dependencies'],
    prNotPendingHours: 48,
    prHourlyLimit: 2,
    prConcurrentLimit: 10,
    packageRules: [
        {
            description: 'Require approval for major updates',
            matchUpdateTypes: ['major'],
            dependencyDashboardApproval: true,
        },
        {
            description: 'Auto-merge minor updates after 1 day',
            matchUpdateTypes: ['minor'],
            automerge: true,
            minimumReleaseAge: '1 day',
        },
        {
            description: 'Auto-merge lockfile maintenance',
            matchUpdateTypes: ['lockFileMaintenance'],
            automerge: true,
            minimumReleaseAge: '0 days',
        },
        {
            description: 'Auto-merge dev dependencies minor and patch updates',
            matchDepTypes: ['devDependencies'],
            matchUpdateTypes: ['minor', 'patch'],
            automerge: true,
        },
        {
            description: 'Add security label for vulnerability fixes',
            matchUpdateTypes: ['patch'],
            matchPackagePatterns: ['.*'],
            vulnerabilityAlertsOnly: true,
            labels: ['type:dependencies', 'security'],
        },
    ],
};
