packages:
    - apps/*
    - packages/*

# Unified React 19 for entire monorepo
# Libraries (packages/*) maintain peerDependencies for React 17/18/19 compatibility
catalog:
    react: ^19.2.4
    react-dom: ^19.2.4
    "@types/react": ^19.2.10
    "@types/react-dom": ^19.2.3
    typescript: ^5.9.2
    eslint: ^10.0.1
    prettier: ^3.3.0
