// file key
const FIGMA_ICONS_FILE_KEY = 'DVgbt41m23pnHjAL8ZYsD3';
const FIGMA_RESOURCE_FILE_KEY = 'hyiokiTlazRVYf0cfEvGUB';
const FIGMA_ICONS_RENEWAL_BRANCH_KEY = '';

// node id
const FIGMA_ICONS_BASIC_FILL_NODE_ID = '6638%3A464';
const FIGMA_ICONS_BASIC_OUTLINE_NODE_ID = '6638%3A3186';
const FIGMA_ICONS_BASIC_NODE_IDS = [
    FIGMA_ICONS_BASIC_FILL_NODE_ID,
    FIGMA_ICONS_BASIC_OUTLINE_NODE_ID,
];
const FIGMA_ICONS_EXTENSION_NODE_ID = '1050%3A554';

const FIGMA_ICONS_SYMBOL_DEFAULT_NODE_ID = '2679%3A155';
const FIGMA_ICONS_SYMBOL_COLOR_NODE_ID = '2669%3A136';

const FIGMA_ICONS_STACK_DEFAULT_NODE_ID = '3610%3A91';
const FIGMA_ICONS_STACK_COLOR_NODE_ID = '3610%3A74';

const FIGMA_RESOURCES_BASIC_IMAGES_NODE_ID = '1142%3A129044';
const FIGMA_RESOURCES_BRAND_IMAGES_NODE_ID = '1734%3A148990';
const FIGMA_RESOURCES_OTHER_BRAND_IMAGES_NODE_ID = '2422%3A27281';

const FIGMA_DOCS_FILE_KEY = 'tzMIJzKp1JJ5F8cjAw4xMz';
const FIGMA_DOCS_ALL_NODE_ID = '31400:61294';
const FIGMA_GUIDES_FILE_KEY = 'tzMIJzKp1JJ5F8cjAw4xMz';

// og-image
const FIGMA_OGIMAGE_FILE_KEY = 'tzMIJzKp1JJ5F8cjAw4xMz';
const FIGMA_OGIMAGE_LOGO_NODE_ID = '1319:24797';
const FIGMA_OGIMAGE_COMPONENTS_CORE_NODE_ID = '1356:23264';

// Figma API Spec
const FIGMA_NODE_TYPES = {
    /**
     * @link https://www.figma.com/developers/api#node-types
     */
    DOCUMENT: 'DOCUMENT',
    CANVAS: 'CANVAS',
    FRAME: 'FRAME',
    COMPONENT: 'COMPONENT',
    COMPONENT_SET: 'COMPONENT_SET',
};

module.exports = {
    FIGMA_ICONS_FILE_KEY,
    FIGMA_ICONS_RENEWAL_BRANCH_KEY,
    FIGMA_ICONS_BASIC_NODE_IDS,
    FIGMA_ICONS_EXTENSION_NODE_ID,
    FIGMA_ICONS_SYMBOL_COLOR_NODE_ID,
    FIGMA_ICONS_SYMBOL_DEFAULT_NODE_ID,
    FIGMA_ICONS_STACK_COLOR_NODE_ID,
    FIGMA_ICONS_STACK_DEFAULT_NODE_ID,

    FIGMA_RESOURCE_FILE_KEY,
    FIGMA_RESOURCES_BASIC_IMAGES_NODE_ID,
    FIGMA_RESOURCES_BRAND_IMAGES_NODE_ID,
    FIGMA_RESOURCES_OTHER_BRAND_IMAGES_NODE_ID,

    FIGMA_NODE_TYPES,
    FIGMA_DOCS_FILE_KEY,
    FIGMA_DOCS_ALL_NODE_ID,
    FIGMA_GUIDES_FILE_KEY,

    FIGMA_OGIMAGE_FILE_KEY,
    FIGMA_OGIMAGE_LOGO_NODE_ID,
    FIGMA_OGIMAGE_COMPONENTS_CORE_NODE_ID,
};
