// file key
const FIGMA_ICONS_FILE_KEY = 'DVgbt41m23pnHjAL8ZYsD3';

// node id
const FIGMA_ICONS_BASIC_FILL_NODE_ID = '6638%3A464';
const FIGMA_ICONS_BASIC_OUTLINE_NODE_ID = '6638%3A3186';
const FIGMA_ICONS_BASIC_NODE_IDS = [
    FIGMA_ICONS_BASIC_FILL_NODE_ID,
    FIGMA_ICONS_BASIC_OUTLINE_NODE_ID,
];

const FIGMA_ICONS_SYMBOL_COLOR_NODE_ID = '2669%3A136';
const FIGMA_ICONS_SYMBOL_DEFAULT_NODE_ID = '2679%3A155';
const FIGMA_ICONS_SYMBOL_COLOR_COUNTRY_NODE_ID = '9199%3A27825';
const FIGMA_ICONS_SYMBOL_NODE_IDS = [
    FIGMA_ICONS_SYMBOL_DEFAULT_NODE_ID,
    FIGMA_ICONS_SYMBOL_COLOR_NODE_ID,
    FIGMA_ICONS_SYMBOL_COLOR_COUNTRY_NODE_ID,
];

// Figma API Spec
const FIGMA_NODE_TYPES = {
    /**
     * @link https://www.figma.com/developers/api#node-types
     */
    Document: 'DOCUMENT',
    Canvas: 'CANVAS',
    Frame: 'FRAME',
    Component: 'COMPONENT',
    ComponentSet: 'COMPONENT_SET',
};

export {
    FIGMA_ICONS_FILE_KEY,
    FIGMA_ICONS_BASIC_NODE_IDS,
    FIGMA_ICONS_SYMBOL_COLOR_NODE_ID,
    FIGMA_ICONS_SYMBOL_DEFAULT_NODE_ID,
    FIGMA_ICONS_SYMBOL_COLOR_COUNTRY_NODE_ID,
    FIGMA_ICONS_SYMBOL_NODE_IDS,
    FIGMA_NODE_TYPES,
};
