export const CONFIG = {
    sourceDir: '../../../apps/website/public/components/generated/en',
    targetDir: '../../../apps/website/public/components/generated/ko',
};

/**
 * Korean translations for props shared across components.
 * These props are pulled from constants without calling the DeepL API.
 */
export const COMMON_PROPS_KO: Record<string, string> = {
    render: 'component의 HTML element를 다른 태그로 교체하거나 다른 component와 조합할 수 있습니다.\n\nReactElement 또는 렌더링할 요소를 반환하는 함수를 받습니다.',
    className: 'component의 root element에 추가할 CSS class입니다.',
};

// Technical terms to keep in English
export const KEEP_ENGLISH_TERMS = [
    // UI components
    'component',
    'button',
    'input',
    'modal',
    'dialog',
    'popover',
    'tooltip',
    'dropdown',
    'checkbox',
    'radio',
    'toggle',
    'switch',
    'slider',
    'tab',
    'accordion',
    'menu',
    'navigation',
    'breadcrumb',
    'pagination',
    'avatar',
    'badge',
    'tag',
    'chip',
    'card',
    'list',
    'table',
    'form',
    'field',
    'label',
    'placeholder',
    'icon',
    'spinner',
    'skeleton',
    'toast',
    'alert',
    'progress',

    // React/dev terms
    'props',
    'state',
    'context',
    'provider',
    'hook',
    'callback',
    'handler',
    'event',
    'listener',
    'trigger',
    'render',
    'mount',
    'unmount',
    'effect',
    'ref',
    'portal',
    'fragment',
    'slot',
    'primitive',
    'controlled',
    'uncontrolled',
    'fallback',
    'suspense',
    'lazy',
    'children',
    'className',

    // State terms
    'disabled',
    'enabled',
    'checked',
    'selected',
    'focused',
    'hovered',
    'loading',
    'error',
    'success',
    'warning',
    'primary',
    'secondary',
    'variant',
    'size',
    'default',
    'required',
    'optional',
    'readonly',
    'open',
    'closed',
    'expanded',
    'collapsed',
    'active',
    'valid',
    'invalid',
];
