import { LIGHT_BASIC_COLORS } from './basic-color';

export const LIGHT_SEMANTIC_COLORS = {
    background: {
        'rgb-primary': '42, 111, 243',
        primary: LIGHT_BASIC_COLORS.blue['500'],
        'rgb-secondary': '232, 232, 238',
        secondary: LIGHT_BASIC_COLORS.gray['200'],
        'rgb-success': '10, 134, 114',
        success: LIGHT_BASIC_COLORS.green['500'],
        'rgb-warning': '209, 73, 5',
        warning: LIGHT_BASIC_COLORS.orange['500'],
        'rgb-danger': '223, 51, 55',
        danger: LIGHT_BASIC_COLORS.red['500'],
        'rgb-hint': '108, 110, 126',
        hint: LIGHT_BASIC_COLORS.gray['600'],
        'rgb-contrast': '62, 64, 76',
        contrast: LIGHT_BASIC_COLORS.gray['800'],
        'rgb-normal': '255, 255, 255',
        normal: LIGHT_BASIC_COLORS.gray['000'],
        'normal-lighter': LIGHT_BASIC_COLORS.gray['000'],
        'normal-darker': LIGHT_BASIC_COLORS.gray['050'],
    },
    foreground: {
        primary: LIGHT_BASIC_COLORS.blue['600'],
        'primary-darker': LIGHT_BASIC_COLORS.blue['700'],
        secondary: LIGHT_BASIC_COLORS.gray['800'],
        'secondary-darker': LIGHT_BASIC_COLORS.gray['900'],
        success: LIGHT_BASIC_COLORS.green['600'],
        'success-darker': LIGHT_BASIC_COLORS.green['700'],
        warning: LIGHT_BASIC_COLORS.orange['600'],
        'warning-darker': LIGHT_BASIC_COLORS.orange['700'],
        danger: LIGHT_BASIC_COLORS.red['600'],
        'danger-darker': LIGHT_BASIC_COLORS.red['700'],
        hint: LIGHT_BASIC_COLORS.gray['600'],
        'hint-darker': LIGHT_BASIC_COLORS.gray['700'],
        contrast: LIGHT_BASIC_COLORS.gray['800'],
        'contrast-darker': LIGHT_BASIC_COLORS.gray['900'],
        accent: LIGHT_BASIC_COLORS.white,
        'accent-darker': LIGHT_BASIC_COLORS.white,
        normal: LIGHT_BASIC_COLORS.gray['900'],
        'normal-lighter': LIGHT_BASIC_COLORS.gray['700'],
    },
    border: {
        normal: LIGHT_BASIC_COLORS.gray['300'],
        primary: LIGHT_BASIC_COLORS.blue['500'],
        secondary: LIGHT_BASIC_COLORS.gray['200'],
        success: LIGHT_BASIC_COLORS.green['500'],
        warning: LIGHT_BASIC_COLORS.orange['500'],
        danger: LIGHT_BASIC_COLORS.red['500'],
        hint: LIGHT_BASIC_COLORS.gray['600'],
        contrast: LIGHT_BASIC_COLORS.gray['800'],
    },
    logo: {
        normal: LIGHT_BASIC_COLORS.gray['900'],
    },
};
