export {
    MultiSelectRoot as Root,
    MultiSelectTrigger as Trigger,
    MultiSelectValue as Value,
    MultiSelectPlaceholder as Placeholder,
    MultiSelectTriggerIcon as TriggerIcon,
    MultiSelectContent as Content,
    MultiSelectPortal as Portal,
    MultiSelectPositioner as Positioner,
    MultiSelectPopup as Popup,
    MultiSelectGroup as Group,
    MultiSelectGroupLabel as GroupLabel,
    MultiSelectItem as Item,
    MultiSelectItemIndicator as ItemIndicator,
    MultiSelectSeparator as Separator,
} from './multi-select';
