name: 'Update Visual Snapshots'

on:
    workflow_dispatch:

jobs:
    update-snapshots:
        runs-on: macos-latest
        steps:
            - name: Git clone the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Dependencies
              uses: ./.github/composite/install

            - name: Install Playwright Browsers
              uses: ./.github/composite/browser-install
              with:
                  working-directory: packages/core

            - name: Configure Git
              run: |
                  git config user.name "$(git log -n 1 --pretty=format:%an)"
                  git config user.email "$(git log -n 1 --pretty=format:%ae)"

            - name: Take a snapshot
              run: |
                  pnpm test:regression --update-snapshots
                  git add packages/core/__tests__/screenshots
                  git diff --exit-code || git commit -m 'ci: update snapshots'

            - name: Update Snapshots
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.VAPOR_BOT_TOKEN }}
                  branch: ${{ github.ref_name }}
